resources:
- name: git-assets
  type: git
  source:
    branch: master
    uri: https://github.com/4craig/concourse-workshop

jobs:
- name: helloresources:
- name: git-assets
  type: git
  source:
    branch: master
    uri: https://github.com/nsagoo-pivotal/concourse-workshop

jobs:
- name: unit-test
  public: true
  plan:
  - get: git-assets
    trigger: true
  - task: mvn-test
    file: git-assets/ci/tasks/mvn-test.yml
- name: deploy
  public: true
  plan:
  - get: git-assets
    trigger: true
    passed:
      - unit-test
  - task: mvn-package
    file: git-assets/ci/tasks/mvn-package.yml
  plan:
  - get: git-assets
    trigger: true
  - task: howdy
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: ubuntu}
      run:
        path: echo
        args: ["Hello, My first pipeline!"]